In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
import pandas as pd
import scipy.stats
import matplotlib.pyplot as plt

import sys
sys.path.append("../../../")

from chiseling.benchmark.benchmark import Benchmark
from chiseling.dgps.basic_binary_regression import search_for_target_specification_binary_regression
from chiseling.dgps.basic_binary_regression import search_for_target_specification_binary_regression_size_only

In [3]:
# Hyperparameters
d = 100
s = 5
rho = 0.2

test_thresh = 0.9

alpha = 0.05

random_seed = 111

In [4]:
target_size = 0.5
theta = 2
n = 1000

n_sims = 20

In [5]:
tau = search_for_target_specification_binary_regression_size_only(d,
                                                                  s,
                                                                  rho,
                                                                  theta,
                                                                  test_thresh,
                                                                  target_size)
print(tau)

2.2066104349423044

In [6]:
settings = {"task_id": 0,
            "dgp": "BasicBinaryRegression",
             "n": n,
             "d": d,
             "s": s,
             "rho": rho,
             "theta": theta,
             "tau": tau,
             "alpha": alpha,
             "random_seed": 42,
             "strategy": "SimulDataSplittingStrategy",
             "train_ratio": 0.5,
             "test_thresh": test_thresh,
             "learner": "logreg_learner",
             "binary": True,
             "randomize": True,
             "n_sims": n_sims,
             "random_seed": random_seed}

In [7]:
benchmark = Benchmark(settings)
benchmark.simulate_batch()
benchmark.simulation_results_df

,task_id,sim_id,rejected,region_mass,subgroup_mean,subgroup_utility,region_mass_se,subgroup_mean_se,subgroup_utility_se
0,0,0,True,0.39300,0.949825,0.019581,0.001545,0.000432,0.000187
1,0,1,True,0.35847,0.956650,0.020307,0.001516,0.000398,0.000167
2,0,2,True,0.50121,0.931186,0.015631,0.001581,0.000485,0.000248
3,0,3,True,0.35294,0.955112,0.019451,0.001511,0.000423,0.000171
4,0,4,True,0.61893,0.901303,0.000806,0.001536,0.000590,0.000365
5,0,5,True,0.17602,0.980574,0.014183,0.001204,0.000292,0.000110
6,0,6,False,0.00000,NaN,0.000000,0.000000,NaN,0.000000
7,0,7,True,0.46650,0.948816,0.022772,0.001578,0.000365,0.000187
8,0,8,True,0.51007,0.927002,0.013773,0.001581,0.000511,0.000264
9,0,9,True,0.42442,0.946335,0.019665,0.001563,0.000432,0.000197
10,0,10,True,0.62442,0.908916,0.005567,0.001531,0.000533,0.000333
11,0,11,True,0.23190,0.965282,0.015139,0.001335,0.000443,0.000135
12,0,12,True,0.59039,0.921513,0.012701,0.001555,0.000478,0.000284
13,0,13,True,0.59556,0.927903,0.016618,0.001552,0.000422,0.000255
14,0,14,True,0.49050,0.932874,0.016124,0.001581,0.000488,0.000245
15,0,15,True,0.56689,0.922845,0.012950,0.001567,0.000490,0.000280
16,0,16,True,0.51500,0.933201,0.017099,0.001580,0.000458,0.000242
17,0,17,True,0.54029,0.934155,0.018454,0.001576,0.000422,0.000234
18,0,18,True,0.48656,0.936667,0.017841,0.001581,0.000457,0.000230
19,0,19,True,0.50081,0.932230,0.016141,0.001581,0.000483,0.000247

In [8]:
(benchmark.simulation_results_df.rejected.mean(),
 np.sqrt(benchmark.simulation_results_df.rejected.var() / n_sims))

(np.float64(0.95), np.float64(0.05000000000000001))

### Settings

- ```size = 0.5, n = 1000, theta = 2, tau = 2.200```
- ```size = 0.25, n = 2000, theta = 1.9, tau = 0.700```
- ```size = 0.1, n = 5000, theta = 1.3, tau = 0.243```
- ```size = 0.05, n = 10000, theta = 0.9, tau = 0.460```
- ```size = 0.01, n = 25000, theta = 1.5, tau = -1.936```