In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
import pandas as pd
import scipy.stats
import matplotlib.pyplot as plt

import sys
sys.path.append("../../../")

from chiseling.benchmark.benchmark import Benchmark
from chiseling.dgps.linear_nonneg_rct import LinearNonNegRCT

In [3]:
# Hyperparameters
d = 3

test_thresh = 0
alpha = 0.05

random_seed = 44

In [4]:
q = 0.5
tau = 0.1 / q
tau0 = 0

n = 1000

n_sims = 50

In [5]:
settings = {"task_id": 0,
            "dgp": "LinearNonNegRCT",
             "n": n,
             "d": d,
             "q": q,
             "tau": tau,
             "tau0": tau0,
             "alpha": alpha,
             "random_seed": 42,
             "strategy": "Chiseling",
             "n_burn_in": 0.05,
             "refit_batch_prop": 0.01,
             "reveal_batch_prop": 0.01,
             "alpha_init": alpha / 2,
             "margin_width": 1,
             "test_thresh": test_thresh,
             "learner": "linreg_learner",
             "n_sims": n_sims,
             "random_seed": random_seed}

# settings = {"task_id": 0,
#             "dgp": "LinearNonNegRCT",
#              "n": n,
#              "d": d,
#              "q": q,
#              "tau": tau,
#              "alpha": alpha,
#              "random_seed": 42,
#              "strategy": "TTestStrategy",
#              "test_thresh": test_thresh,
#              "n_sims": n_sims,
#              "random_seed": random_seed}

In [6]:
benchmark = Benchmark(settings)
benchmark.simulate_batch()
benchmark.simulation_results_df

,task_id,sim_id,rejected,region_mass,subgroup_mean,subgroup_utility,region_mass_se,subgroup_mean_se,subgroup_utility_se
0,0,0,False,0.00000,NaN,0.000000,0.000000,NaN,0.000000
1,0,1,False,0.00000,NaN,0.000000,0.000000,NaN,0.000000
2,0,2,True,0.50326,0.197564,0.099426,0.001581,9.779274e-05,0.000316
3,0,3,False,0.00000,NaN,0.000000,0.000000,NaN,0.000000
4,0,4,False,0.00000,NaN,0.000000,0.000000,NaN,0.000000
5,0,5,False,0.00000,NaN,0.000000,0.000000,NaN,0.000000
6,0,6,True,1.00000,0.099820,0.099820,0.000000,3.162273e-04,0.000316
7,0,7,False,0.00000,NaN,0.000000,0.000000,NaN,0.000000
8,0,8,False,0.00000,NaN,0.000000,0.000000,NaN,0.000000
9,0,9,True,0.30681,0.196917,0.060416,0.001458,1.406751e-04,0.000290
10,0,10,True,1.00000,0.099664,0.099664,0.000000,3.162260e-04,0.000316
11,0,11,True,1.00000,0.100034,0.100034,0.000000,3.162277e-04,0.000316
12,0,12,True,0.25306,0.194515,0.049224,0.001375,2.053279e-04,0.000272
13,0,13,True,1.00000,0.099634,0.099634,0.000000,3.162256e-04,0.000316
14,0,14,True,1.00000,0.099824,0.099824,0.000000,3.162273e-04,0.000316
15,0,15,False,0.00000,NaN,0.000000,0.000000,NaN,0.000000
16,0,16,True,1.00000,0.099698,0.099698,0.000000,3.162263e-04,0.000316
17,0,17,True,1.00000,0.100576,0.100576,0.000000,3.162225e-04,0.000316
18,0,18,False,0.00000,NaN,0.000000,0.000000,NaN,0.000000
19,0,19,True,1.00000,0.099568,0.099568,0.000000,3.162248e-04,0.000316
20,0,20,True,1.00000,0.099738,0.099738,0.000000,3.162267e-04,0.000316
21,0,21,False,0.00000,NaN,0.000000,0.000000,NaN,0.000000
22,0,22,True,0.95294,0.105295,0.100340,0.000670,3.234875e-04,0.000316
23,0,23,True,0.90437,0.109020,0.098594,0.000930,3.311717e-04,0.000316
24,0,24,True,0.52767,0.117930,0.062228,0.001579,4.282756e-04,0.000293
25,0,25,False,0.00000,NaN,0.000000,0.000000,NaN,0.000000
26,0,26,True,1.00000,0.100268,0.100268,0.000000,3.162266e-04,0.000316
27,0,27,False,0.00000,NaN,0.000000,0.000000,NaN,0.000000
28,0,28,True,0.60646,0.163262,0.099012,0.001545,3.144838e-04,0.000316
29,0,29,False,0.00000,NaN,0.000000,0.000000,NaN,0.000000
30,0,30,False,0.00000,NaN,0.000000,0.000000,NaN,0.000000
31,0,31,True,1.00000,0.100164,0.100164,0.000000,3.162273e-04,0.000316
32,0,32,True,0.28338,0.174995,0.049590,0.001425,3.929559e-04,0.000273
33,0,33,True,0.60360,0.147999,0.089332,0.001547,3.570767e-04,0.000314
34,0,34,True,0.20400,0.200000,0.040800,0.001274,1.943279e-19,0.000255
35,0,35,True,1.00000,0.099466,0.099466,0.000000,3.162233e-04,0.000316
36,0,36,False,0.00000,NaN,0.000000,0.000000,NaN,0.000000
37,0,37,True,0.63656,0.138388,0.088092,0.001521,3.659848e-04,0.000314
38,0,38,True,0.43550,0.195780,0.085262,0.001568,1.377426e-04,0.000313
39,0,39,True,0.51787,0.169178,0.087612,0.001580,3.173177e-04,0.000314
40,0,40,True,0.28660,0.179086,0.051326,0.001430,3.615037e-04,0.000276
41,0,41,False,0.00000,NaN,0.000000,0.000000,NaN,0.000000
42,0,42,False,0.00000,NaN,0.000000,0.000000,NaN,0.000000
43,0,43,False,0.00000,NaN,0.000000,0.000000,NaN,0.000000
44,0,44,True,1.00000,0.100100,0.100100,0.000000,3.162276e-04,0.000316
45,0,45,True,1.00000,0.100060,0.100060,0.000000,3.162277e-04,0.000316
46,0,46,False,0.00000,NaN,0.000000,0.000000,NaN,0.000000
47,0,47,True,1.00000,0.100200,0.100200,0.000000,3.162271e-04,0.000316
48,0,48,True,1.00000,0.100072,0.100072,0.000000,3.162277e-04,0.000316
49,0,49,True,1.00000,0.100306,0.100306,0.000000,3.162263e-04,0.000316

In [7]:
(benchmark.simulation_results_df.rejected.mean(),
 np.sqrt(benchmark.simulation_results_df.rejected.var() / n_sims))

(np.float64(0.62), np.float64(0.06934092056863769))