In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
import pandas as pd
import scipy.stats
import matplotlib.pyplot as plt

import sys
sys.path.append("../../../")

from chiseling.benchmark.benchmark import Benchmark
from chiseling.dgps.nonneg_rct import NonNegRCT

In [3]:
# Hyperparameters
d = 2
s = 2

test_thresh = 0
alpha = 0.05

random_seed = 112

In [4]:
q = 0.1
tau = 0.1 / q

n = 1000

n_sims = 30

In [5]:
# settings = {"task_id": 0,
#             "dgp": "NonNegRCT",
#              "n": n,
#              "d": d,
#              "s": s,
#              "q": q,
#              "tau": tau,
#              "alpha": alpha,
#              "random_seed": 42,
#              "strategy": "Chiseling",
#              "n_burn_in": 0.2,
#              "refit_batch_prop": 0.1,
#              "alpha_init": alpha / 2,
#              "margin_width": 1,
#              "test_thresh": test_thresh,
#              "learner": "nonneg_rct_causal_random_forest_learner",
#              "n_sims": n_sims,
#              "random_seed": random_seed}

settings = {"task_id": 0,
            "dgp": "NonNegRCT",
             "n": n,
             "d": d,
             "s": s,
             "q": q,
             "tau": tau,
             "alpha": alpha,
             "random_seed": 42,
             "strategy": "OracleStrategy",
             "test_thresh": test_thresh,
             "learner": "nonneg_rct_causal_random_forest_learner",
             "n_sims": n_sims,
             "random_seed": random_seed}

# settings = {"task_id": 0,
#             "dgp": "NonNegRCT",
#              "n": n,
#              "d": d,
#              "s": s,
#              "q": q,
#              "tau": tau,
#              "alpha": alpha,
#              "random_seed": 42,
#              "strategy": "TTestStrategy",
#              "test_thresh": test_thresh,
#              "n_sims": n_sims,
#              "random_seed": random_seed}

In [6]:
benchmark = Benchmark(settings)
benchmark.simulate_batch()
benchmark.simulation_results_df

,task_id,sim_id,rejected,region_mass,subgroup_mean,subgroup_utility,region_mass_se,subgroup_mean_se,subgroup_utility_se
0,0,0,True,0.69287,0.144601,0.10019,0.001459,0.001336,0.000949
1,0,1,True,0.57863,0.171699,0.09935,0.001561,0.001568,0.000946
2,0,2,False,0.00000,NaN,0.00000,0.000000,NaN,0.000000
3,0,3,True,0.77014,0.128029,0.09860,0.001331,0.001204,0.000943
4,0,4,False,0.00000,NaN,0.00000,0.000000,NaN,0.000000
5,0,5,True,0.46233,0.218459,0.10100,0.001577,0.001922,0.000953
6,0,6,True,0.70688,0.141354,0.09992,0.001439,0.001310,0.000948
7,0,7,True,0.67199,0.149333,0.10035,0.001485,0.001375,0.000950
8,0,8,True,0.75897,0.131033,0.09945,0.001353,0.001225,0.000946
9,0,9,True,0.75398,0.130919,0.09871,0.001362,0.001228,0.000943
10,0,10,True,0.48085,0.206010,0.09906,0.001580,0.001844,0.000945
11,0,11,True,0.64217,0.157030,0.10084,0.001516,0.001436,0.000952
12,0,12,True,0.85704,0.117824,0.10098,0.001107,0.001101,0.000953
13,0,13,True,0.48306,0.206372,0.09969,0.001580,0.001841,0.000947
14,0,14,False,0.00000,NaN,0.00000,0.000000,NaN,0.000000
15,0,15,True,0.50741,0.197631,0.10028,0.001581,0.001768,0.000950
16,0,16,False,0.00000,NaN,0.00000,0.000000,NaN,0.000000
17,0,17,True,0.27306,0.365158,0.09971,0.001409,0.002914,0.000947
18,0,18,True,0.42830,0.228975,0.09807,0.001565,0.002030,0.000940
19,0,19,False,0.00000,NaN,0.00000,0.000000,NaN,0.000000
20,0,20,False,0.00000,NaN,0.00000,0.000000,NaN,0.000000
21,0,21,True,0.77468,0.127691,0.09892,0.001321,0.001199,0.000944
22,0,22,True,0.41506,0.237990,0.09878,0.001558,0.002090,0.000944
23,0,23,False,0.00000,NaN,0.00000,0.000000,NaN,0.000000
24,0,24,False,0.00000,NaN,0.00000,0.000000,NaN,0.000000
25,0,25,True,0.28088,0.340288,0.09558,0.001421,0.002827,0.000930
26,0,26,True,0.45083,0.224231,0.10109,0.001573,0.001964,0.000953
27,0,27,True,0.38672,0.262153,0.10138,0.001540,0.002236,0.000954
28,0,28,True,0.77443,0.128688,0.09966,0.001322,0.001203,0.000947
29,0,29,False,0.00000,NaN,0.00000,0.000000,NaN,0.000000

In [7]:
(benchmark.simulation_results_df.rejected.mean(),
 np.sqrt(benchmark.simulation_results_df.rejected.var() / n_sims))

(np.float64(0.7), np.float64(0.0850962943396763))